-- Up
CREATE TABLE `users` (
  `id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
  `username` TEXT NOT NULL UNIQUE,
  `password` TEXT NOT NULL,
  `created` INTEGER NOT NULL
);

-- Down
DROP TABLE `users`;
